name: Spry
favicon: null
layout_spectrum: 0.90783
typography_spectrum: 0.20214256760664284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#373b3e'
    - '#004c00'
    - '#1a7f19'
    - '#460973'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.4011844052001834
  rhythmicContrast: 0.44129946967586875
purpose: []
