name: Spry
favicon: null
layout_spectrum: 0.1236
typography_spectrum: 0.65317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4c7ef'
    - '#796753'
    - '#f7e8e3'
    - '#2b2c31'
    - '#000004'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
