name: Spry
favicon: null
layout_spectrum: 0.3226973384153098
typography_spectrum: 0.20214256760664284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.549996723420918
  lightness: 0.33551101735793054
  saturation: 0.4011844052001834
  rhythmicContrast: 0.44129946967586875
purpose: []
