name: Spry
favicon: null
layout_spectrum: 0.82047
typography_spectrum: 0.65317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#373b3e'
    - '#004c00'
    - '#1a7f19'
    - '#460973'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
